version: "3"

services:
  nginx:
    image: nginx
    ports:
      - ${HTTP_PORT}:80
    volumes:
      - ./frontend/dist:/var/www/public
      - ./etc/nginx/site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  backend:
    image: metaa/node-alpine-glibc
    ports:
      - ${BACKEND_DEBUG_PORT}:9229
    depends_on:
      - mongo
    volumes:
      - ./backend:/var/www
    working_dir: /var/www
    environment:
      - NODE_ENV=development
      - MONGO_HOST=mongo
      - MONGO_DB=hripto
      - BITGO_ACCESS_TOKEN=${BITGO_ACCESS_TOKEN}
      - BITGO_ENV=${BITGO_ENV}
    command: npm run start

  mongo:
    image: mongo
    volumes:
      - ./etc/database:/data/db
    ports:
      - ${MONGO_PORT}:27017